version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front End installation
          command: npm run frontend:install
      - run:
          name: Back End Installation
          command: npm run api:install
      - run:
          name: Front End Build production
          command: npm run frontend:build
      - run:
          name: Back End Build production
          command: npm run api:build
      - run:
          name: Deploy Back End production on server
          command: npm run api:deploy
      - run:
          name: Deploy Front End production on server
          command: npm run frontend:deploy          
workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main